<?php

$subjects = array (
  6 => 
  array (
    0 => 'Mathematics',
    1 => 'French',
    2 => 'ICT',
    3 => 'Art',
    4 => 'English Language',
    5 => 'Social Studies',
    6 => 'Music',
    7 => 'STEM',
    8 => 'Social emotional learning',
    9 => 'Science',
    10 => 'Coding',
    11 => 'Bible',
  ),
  7 => 
  array (
    0 => 'Mathematics',
    1 => 'French',
    2 => 'ICT',
    3 => 'Art',
    4 => 'English Language',
    5 => 'Social Studies',
    6 => 'Music',
    7 => 'STEM',
    8 => 'Social emotional learning',
    9 => 'Science',
    10 => 'Coding',
    11 => 'Bible',
  ),
  8 => 
  array (
    0 => 'Mathematics',
    1 => 'French',
    2 => 'ICT',
    3 => 'Art',
    4 => 'English Language',
    5 => 'Social Studies',
    6 => 'Music',
    7 => 'STEM',
    8 => 'Social emotional learning',
    9 => 'Science',
    10 => 'Coding',
    11 => 'Bible',
    12 => 'Design Technology',
  ),
  9 => 
  array (
    0 => 'Chemistry(UK)',
    1 => 'Business Studies(UK)',
    2 => 'Geography(UK)',
    3 => 'Mathemathics(UK)',
    4 => 'Art(UK)',
    5 => 'Additional Mathematics(UK)',
    6 => 'English(UK)',
    7 => 'English second language(UK)',
    8 => 'Literature(UK)',
    9 => 'Mathematics Core(UK)',
    10 => 'ICT(UK)',
    11 => 'Physics(UK)',
    12 => 'Music(UK)',
    13 => 'French(UK)',
    14 => 'Coding(UK)',
    15 => 'Economics(UK)',
    16 => 'Biology(UK)',
    17 => 'Design & Technology(UK)',
    18 => 'World History(US)',
    19 => 'Art(US)',
    20 => 'Music(US)',
    21 => 'Biology(US)',
    22 => 'Information Technology(US)',
    23 => 'French(US)',
    24 => 'English(US)',
    25 => 'Math(US)',
    26 => 'Coding(US)',
    27 => 'PreAP(US)',
  ),
  10 => 
  array (
    0 => 'Economics(UK)',
    1 => 'Design & Technology(UK)',
    2 => 'Literature(UK)',
    3 => 'Physics(UK)',
    4 => 'Music(UK)',
    5 => 'Biology(UK)',
    6 => 'Additional Math(UK)',
    7 => 'Business Studies(UK)',
    8 => 'Mathematics(UK)',
    9 => 'Math Core(UK)',
    10 => 'English(UK)',
    11 => 'French(UK)',
    12 => 'Art(UK)',
    13 => 'Chemistry(UK)',
    14 => 'ICT(UK)',
    15 => 'Art(US)',
    16 => 'Music(US)',
    17 => 'English Regular(US)',
    18 => 'AP Seminar(US)',
    19 => 'PreCalculus(US)',
    20 => 'Mathematics(US)',
    21 => 'French(US)',
    22 => 'Chemistry(US)',
    23 => 'Human Geography(US)',
    24 => 'Psychology(US)',
    25 => 'SAT English(US)',
    26 => 'Computer Science(US)',
    27 => 'History(US)',
    28 => 'Coding(US)',
    29 => 'Community Service(US)',
    
  ),
  11 => 
  array (
    0 => 'IT(UK)',
    1 => 'Biology(UK)',
    2 => 'Psychology(UK)',
    3 => 'Physics(UK)',
    4 => 'Economics(UK)',
    5 => 'Mathematics(UK)',
    6 => 'English(UK)',
    7 => 'AS English(UK)',
    8 => 'Chemistry(UK)',
    9 => 'Business Studies(US)',
    10 => 'PreCalculus(US)',
    11 => 'English Regular(US)',
    12 => 'French(US)',
    13 => 'Biology(US)',
    14 => 'AP Seminar(US)',
    15 => 'AP English(US)',
    16 => 'Physics(US)',
    17 => 'Microeconomics(US)',
    18 => 'Mathematics(US)',
    19 => 'Chemistry(US)',
    20 => 'Art(US)',
    21 => 'Music(US)',
    22 => 'Computer Science(US)',
    23 => 'Economics(US)',
    24 => 'AP Computer Science(US)',
    25 => 'Design Technology(US)',
    26 => 'AP Psychology(US)',
    27 => 'AP Chemistry(US)',
    28 => 'English as Second Language(US)',
    29 => 'Mathematics Regular(US)',
    30 => 'Coding(US)',
    31 => 'AP Physics(US)',
    32 => 'AP Art(US)',
    33 => 'Sociology(US)',
    34 => 'Health Wellness(US)',
  ),
  12 => 
  array (
    0 => 'IT(UK)',
    1 => 'Biology(UK)',
    2 => 'Psychology(UK)',
    3 => 'Physics(UK)',
    4 => 'Economics(UK)',
    5 => 'Mathematics(UK)',
    6 => 'Design and Technology(UK)',
    7 => 'Chemistry(UK)',
    8 => 'Business Studies(US)',
    9 => 'Calculus(US)',
    10 => 'English Regular(US)',
    11 => 'French(US)',
    12 => 'Biology(US)',
    13 => 'AP Seminar(US)',
    14 => 'AP English(US)',
    15 => 'Physics(US)',
    16 => 'Macroeconomics(US)',
    17 => 'Mathematics(US)',
    18 => 'Chemistry(US)',
    19 => 'Art(US)',
    20 => 'Music(US)',
    21 => 'Computer Science(US)',
    22 => 'Economics(US)',
    23 => 'AP Computer Science(US)',
    24 => 'Design Technology(US)',
    25 => 'AP Psychology(US)',
    26 => 'AP Chemistry(US)',
    27 => 'English as Second Language(US)',
    28 => 'Mathematics Regular(US)',
    29 => 'Coding(US)',
    30 => 'AP Physics(US)',
    31 => 'AP Art(US)',
    32 => 'Sociology(US)',
    33 => 'Environmental Science(US)',
    34 => 'AP Biology(US)',

  ),

);

?>